### ISSUE TITLE
刷入后无法启动

### ISSUE THREAD

**Issue by giveup** [bin456789/KernelSU-Action#3]
系统 pixel experience 13
设备 dipper
和pe的boot镜像对比了发现大小也不一致。
pe的是64M，action编译的是25.5M 
尝试了adb sideload boot.zip / fastboot flash boot image两种方法，都无法启动。

**Comment by bin456789** [comment]
大小是正常的，因为编译出来只有内核部分
使用时先刷入64m的boot.img
再 adb sideload boot.zip

**Comment by giveup** [comment]
意思是说先fastboot刷入pe原本的boot.img（64M），再adb sideload action的编译产物boot.zip吗？
--
这样刷了也不行。会卡fastboot界面。能否给出简易的操作说明？

**Comment by bin456789** [comment]
是的

**Comment by giveup** [comment]
> 是的

这个步骤已经尝试过了。会卡fastboot界面。请问有无简易的使用说明？

**Comment by bin456789** [comment]
那就奇怪了，我自己就在用 dipper PE 13

**Comment by bin456789** [comment]
![1](https://github.com/bin456789/KernelSU-Action/assets/7548515/755a6aed-ee42-4eef-b43a-94cbb13525da)

**Comment by bin456789** [comment]
要用官方的 rec
再不行我也没办法了

**Comment by giveup** [comment]
> 那就奇怪了，我自己就在用 dipper PE 13

方便提取一份你的boot镜像吗？我试试直接fastboot刷入你的镜像。
目前我已经尝试过的步骤。
fastboot 刷入原PE 64M的boot.img（尝试过magisk修补和未修补的）
adb sideload action编译的boot.zip
均会卡在fastboot界面。

**Comment by bin456789** [comment]
[boot.zip](https://github.com/bin456789/KernelSU-Action/files/13110989/boot.zip)

**Comment by giveup** [comment]
> [boot.zip](https://github.com/bin456789/KernelSU-Action/files/13110989/boot.zip)

这个镜像刷入后可以启动，谢谢。

**Comment by giveup** [comment]
> [boot.zip](https://github.com/bin456789/KernelSU-Action/files/13110989/boot.zip)

刷入这个镜像后，再sideload新的boot.zip可以正常更新kernelSU。
